/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DAO.FormaPagamentoDAO;
import Model.bean.FormaPagamento;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rayri
 */
public class viewFormaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form viewFormaPagamento
     */
    public viewFormaPagamento() {
        initComponents();
        readTable();
        modelButton();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(32, 136, 203));
        jtPagamento.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jtPagamento.getTableHeader().setOpaque(false);
        jtPagamento.getTableHeader().setBackground(new Color(32, 136, 203));
        jtPagamento.getTableHeader().setForeground(new Color(255, 255, 255));
        jtPagamento.setRowHeight(25);
    }
    
    public void readTable(){
        DefaultTableModel model = (DefaultTableModel) jtPagamento.getModel();
        jtPagamento.setRowSorter(new TableRowSorter(model));
        model.setNumRows(0);
        FormaPagamentoDAO fpdao = new FormaPagamentoDAO();
        for(FormaPagamento fp : fpdao.read()){
            model.addRow(new Object[]{
                fp.getId(),
                fp.getNome(),
            });
        }
    }
    
    public void modelButton(){
        buttonAdicionar.setContentAreaFilled(false);
        buttonAdicionar.setOpaque(true);
        buttonAdicionar.setBackground(new Color(32,136,203));
        buttonDeletar.setContentAreaFilled(false);
        buttonDeletar.setOpaque(true);
        buttonDeletar.setBackground(new Color(32,136,203));
        buttonFechar.setContentAreaFilled(false);
        buttonFechar.setOpaque(true);
        buttonFechar.setBackground(new Color(32,136,203));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPagamento = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonAdicionar = new javax.swing.JButton();
        buttonDeletar = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "TIPO DE PAGAMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPagamento.setFocusable(false);
        jtPagamento.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jtPagamento.setRowHeight(25);
        jtPagamento.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jtPagamento.setShowVerticalLines(false);
        jtPagamento.getTableHeader().setReorderingAllowed(false);
        jtPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPagamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPagamento);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 136, 203));
        jLabel1.setText("FORMA DE PAGAMENTO");

        buttonAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdicionar.setText("ADICIONAR");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        buttonDeletar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonDeletar.setForeground(new java.awt.Color(255, 255, 255));
        buttonDeletar.setText("DELETAR");
        buttonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarActionPerformed(evt);
            }
        });

        buttonFechar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonFechar.setForeground(new java.awt.Color(255, 255, 255));
        buttonFechar.setText("FECHAR");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonFechar))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionar)
                    .addComponent(buttonDeletar)
                    .addComponent(buttonFechar)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPagamentoMouseClicked
      /*  if(jtProdutos.getSelectedRow() > (-1)){
            CategoriaDAO cdao = new CategoriaDAO();
            txtNome.setText(jtProdutos.getValueAt(jtProdutos.getSelectedRow(),2).toString());
            txtPreco.setText(jtProdutos.getValueAt(jtProdutos.getSelectedRow(),3).toString());
            txtQtd.setText(jtProdutos.getValueAt(jtProdutos.getSelectedRow(),4).toString());
            txtCodBarras.setText(jtProdutos.getValueAt(jtProdutos.getSelectedRow(),1).toString());
            for(Categoria cat : cdao.read()){
                if(cat.getNome() == null ? jtProdutos.getValueAt(jtProdutos.getSelectedRow(),5).toString() == null : cat.getNome().equals(jtProdutos.getValueAt(jtProdutos.getSelectedRow(),5).toString())){
                    cbCategoria.setSelectedIndex(cat.getId() - 1);
                }
            }
        }*/
    }//GEN-LAST:event_jtPagamentoMouseClicked

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarActionPerformed
        if(jtPagamento.getSelectedRow() > (-1)){
            FormaPagamento fp = new FormaPagamento();
            FormaPagamentoDAO fpdao = new FormaPagamentoDAO();
            fp.setId((int) jtPagamento.getValueAt(jtPagamento.getSelectedRow(),0));
            fpdao.delete(fp);
            readTable();
        }else{
            JOptionPane.showMessageDialog(null, "NENHUM CAMPO SELECIONADO");
        }
    }//GEN-LAST:event_buttonDeletarActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        FormaPagamento fp = new FormaPagamento();
        FormaPagamentoDAO fpdao = new FormaPagamentoDAO();
        fp.setNome(txtNome.getText());
        fpdao.create(fp);
        txtNome.setText("");
        readTable();
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_buttonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFormaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPagamento;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
